"""add tbl knowledge_base

Revision ID: ee3deb3a3314
Revises: ac3a6245a11e
Create Date: 2026-06-01 18:55:53.443768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee3deb3a3314'
down_revision: Union[str, Sequence[str], None] = 'ac3a6245a11e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_base',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='文件ID'),
    sa.Column('filename', sa.String(length=100), nullable=False, comment='文件名'),
    sa.Column('filepath', sa.String(length=200), nullable=False, comment='文件路径'),
    sa.Column('filetype', sa.String(length=10), nullable=False, comment='文件类型'),
    sa.Column('filesize', sa.BigInteger(), nullable=False, comment='文件大小'),
    sa.Column('md5', sa.String(length=32), nullable=False, comment='md5值'),
    sa.Column('create_by', sa.String(length=64), server_default='', nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), server_default='', nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='知识库表'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_base')
    # ### end Alembic commands ###
