"""add tbl dish user chat_session

Revision ID: 5e687dcaacd1
Revises: b7c8d9e0f1a2
Create Date: 2026-06-01 22:05:01.149247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e687dcaacd1'
down_revision: Union[str, Sequence[str], None] = 'b7c8d9e0f1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('agent_chat_message_session_id_idx'), table_name='agent_chat_message')
    op.drop_index(op.f('agent_chat_message_user_id_idx'), table_name='agent_chat_message')
    op.create_index(op.f('ix_agent_chat_message_session_id'), 'agent_chat_message', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_chat_message_user_id'), 'agent_chat_message', ['user_id'], unique=False)
    op.drop_index(op.f('dish_user_id_idx'), table_name='dish')
    op.create_index(op.f('ix_dish_user_id'), 'dish', ['user_id'], unique=False)
    op.drop_index(op.f('user_email_key'), table_name='user')
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index(op.f('user_email_key'), 'user', ['email'], unique=True)
    op.drop_index(op.f('ix_dish_user_id'), table_name='dish')
    op.create_index(op.f('dish_user_id_idx'), 'dish', ['user_id'], unique=False)
    op.drop_index(op.f('ix_agent_chat_message_user_id'), table_name='agent_chat_message')
    op.drop_index(op.f('ix_agent_chat_message_session_id'), table_name='agent_chat_message')
    op.create_index(op.f('agent_chat_message_user_id_idx'), 'agent_chat_message', ['user_id'], unique=False)
    op.create_index(op.f('agent_chat_message_session_id_idx'), 'agent_chat_message', ['session_id'], unique=False)
    # ### end Alembic commands ###
