"""ini

Revision ID: ac3a6245a11e
Revises: 
Create Date: 2026-05-30 13:12:55.091843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac3a6245a11e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gen_table',
    sa.Column('table_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='编号'),
    sa.Column('table_name', sa.String(length=200), server_default='', nullable=True, comment='表名称'),
    sa.Column('table_comment', sa.String(length=500), server_default='', nullable=True, comment='表描述'),
    sa.Column('sub_table_name', sa.String(length=64), server_default=sa.text('NULL'), nullable=True, comment='关联子表的表名'),
    sa.Column('sub_table_fk_name', sa.String(length=64), server_default=sa.text('NULL'), nullable=True, comment='子表关联的外键名'),
    sa.Column('class_name', sa.String(length=100), server_default='', nullable=True, comment='实体类名称'),
    sa.Column('tpl_category', sa.String(length=200), server_default='crud', nullable=True, comment='使用的模板（crud单表操作 tree树表操作）'),
    sa.Column('tpl_web_type', sa.String(length=30), server_default='', nullable=True, comment='前端模板类型（element-ui模版 element-plus模版）'),
    sa.Column('package_name', sa.String(length=100), nullable=True, comment='生成包路径'),
    sa.Column('module_name', sa.String(length=30), nullable=True, comment='生成模块名'),
    sa.Column('business_name', sa.String(length=30), nullable=True, comment='生成业务名'),
    sa.Column('function_name', sa.String(length=50), nullable=True, comment='生成功能名'),
    sa.Column('function_author', sa.String(length=50), nullable=True, comment='生成功能作者'),
    sa.Column('gen_type', sa.CHAR(length=1), server_default='0', nullable=True, comment='生成代码方式（0zip压缩包 1自定义路径）'),
    sa.Column('gen_path', sa.String(length=200), server_default='/', nullable=True, comment='生成路径（不填默认项目路径）'),
    sa.Column('options', sa.String(length=1000), nullable=True, comment='其它生成选项'),
    sa.Column('create_by', sa.String(length=64), server_default='', nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), server_default='', nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), server_default=sa.text('NULL'), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('table_id'),
    comment='代码生成业务表'
    )
    op.create_table('gen_table_column',
    sa.Column('column_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='编号'),
    sa.Column('table_id', sa.BigInteger(), nullable=True, comment='归属表编号'),
    sa.Column('column_name', sa.String(length=200), nullable=True, comment='列名称'),
    sa.Column('column_comment', sa.String(length=500), nullable=True, comment='列描述'),
    sa.Column('column_type', sa.String(length=100), nullable=True, comment='列类型'),
    sa.Column('python_type', sa.String(length=500), nullable=True, comment='PYTHON类型'),
    sa.Column('python_field', sa.String(length=200), nullable=True, comment='PYTHON字段名'),
    sa.Column('is_pk', sa.CHAR(length=1), nullable=True, comment='是否主键（1是）'),
    sa.Column('is_increment', sa.CHAR(length=1), nullable=True, comment='是否自增（1是）'),
    sa.Column('is_required', sa.CHAR(length=1), nullable=True, comment='是否必填（1是）'),
    sa.Column('is_unique', sa.CHAR(length=1), nullable=True, comment='是否唯一（1是）'),
    sa.Column('is_insert', sa.CHAR(length=1), nullable=True, comment='是否为插入字段（1是）'),
    sa.Column('is_edit', sa.CHAR(length=1), nullable=True, comment='是否编辑字段（1是）'),
    sa.Column('is_list', sa.CHAR(length=1), nullable=True, comment='是否列表字段（1是）'),
    sa.Column('is_query', sa.CHAR(length=1), nullable=True, comment='是否查询字段（1是）'),
    sa.Column('query_type', sa.String(length=200), server_default='EQ', nullable=True, comment='查询方式（等于、不等于、大于、小于、范围）'),
    sa.Column('html_type', sa.String(length=200), nullable=True, comment='显示类型（文本框、文本域、下拉框、复选框、单选框、日期控件）'),
    sa.Column('dict_type', sa.String(length=200), server_default='', nullable=True, comment='字典类型'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('create_by', sa.String(length=64), server_default='', nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), server_default='', nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('column_id'),
    comment='代码生成业务表字段'
    )
    op.create_table('sys_config',
    sa.Column('config_id', sa.Integer(), autoincrement=True, nullable=False, comment='参数主键'),
    sa.Column('config_name', sa.String(length=100), server_default='', nullable=True, comment='参数名称'),
    sa.Column('config_key', sa.String(length=100), server_default='', nullable=True, comment='参数键名'),
    sa.Column('config_value', sa.String(length=500), server_default='', nullable=True, comment='参数键值'),
    sa.Column('config_type', sa.CHAR(length=1), server_default='N', nullable=True, comment='系统内置（Y是 N否）'),
    sa.Column('create_by', sa.String(length=64), server_default='', nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), server_default='', nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), server_default=sa.text('NULL'), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('config_id'),
    comment='参数配置表'
    )
    op.create_table('sys_dept',
    sa.Column('dept_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='部门id'),
    sa.Column('parent_id', sa.BigInteger(), server_default='0', nullable=True, comment='父部门id'),
    sa.Column('ancestors', sa.String(length=50), server_default='', nullable=True, comment='祖级列表'),
    sa.Column('dept_name', sa.String(length=30), server_default='', nullable=True, comment='部门名称'),
    sa.Column('order_num', sa.Integer(), server_default='0', nullable=True, comment='显示顺序'),
    sa.Column('leader', sa.String(length=20), server_default=sa.text('NULL'), nullable=True, comment='负责人'),
    sa.Column('phone', sa.String(length=11), server_default=sa.text('NULL'), nullable=True, comment='联系电话'),
    sa.Column('email', sa.String(length=50), server_default=sa.text('NULL'), nullable=True, comment='邮箱'),
    sa.Column('status', sa.CHAR(length=1), server_default='0', nullable=True, comment='部门状态（0正常 1停用）'),
    sa.Column('del_flag', sa.CHAR(length=1), server_default='0', nullable=True, comment='删除标志（0代表存在 2代表删除）'),
    sa.Column('create_by', sa.String(length=64), server_default='', nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), server_default='', nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('dept_id'),
    comment='部门表'
    )
    op.create_table('sys_dict_data',
    sa.Column('dict_code', sa.BigInteger(), autoincrement=True, nullable=False, comment='字典编码'),
    sa.Column('dict_sort', sa.Integer(), server_default='0', nullable=True, comment='字典排序'),
    sa.Column('dict_label', sa.String(length=100), server_default='', nullable=True, comment='字典标签'),
    sa.Column('dict_value', sa.String(length=100), server_default='', nullable=True, comment='字典键值'),
    sa.Column('dict_type', sa.String(length=100), server_default='', nullable=True, comment='字典类型'),
    sa.Column('css_class', sa.String(length=100), server_default=sa.text('NULL'), nullable=True, comment='样式属性（其他样式扩展）'),
    sa.Column('list_class', sa.String(length=100), server_default=sa.text('NULL'), nullable=True, comment='表格回显样式'),
    sa.Column('is_default', sa.CHAR(length=1), server_default='N', nullable=True, comment='是否默认（Y是 N否）'),
    sa.Column('status', sa.CHAR(length=1), server_default='0', nullable=True, comment='状态（0正常 1停用）'),
    sa.Column('create_by', sa.String(length=64), server_default='', nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), server_default='', nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), server_default=sa.text('NULL'), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('dict_code'),
    comment='字典数据表'
    )
    op.create_table('sys_dict_type',
    sa.Column('dict_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='字典主键'),
    sa.Column('dict_name', sa.String(length=100), server_default='', nullable=True, comment='字典名称'),
    sa.Column('dict_type', sa.String(length=100), server_default='', nullable=True, comment='字典类型'),
    sa.Column('status', sa.CHAR(length=1), server_default='0', nullable=True, comment='状态（0正常 1停用）'),
    sa.Column('create_by', sa.String(length=64), server_default='', nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), server_default='', nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), server_default=sa.text('NULL'), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('dict_id'),
    sa.UniqueConstraint('dict_type'),
    comment='字典类型表'
    )
    op.create_table('sys_job',
    sa.Column('job_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='任务ID'),
    sa.Column('job_name', sa.String(length=64), server_default='', nullable=False, comment='任务名称'),
    sa.Column('job_group', sa.String(length=64), server_default='default', nullable=False, comment='任务组名'),
    sa.Column('job_executor', sa.String(length=64), server_default='default', nullable=True, comment='任务执行器'),
    sa.Column('invoke_target', sa.String(length=500), nullable=False, comment='调用目标字符串'),
    sa.Column('job_args', sa.String(length=255), server_default='', nullable=True, comment='位置参数'),
    sa.Column('job_kwargs', sa.String(length=255), server_default='', nullable=True, comment='关键字参数'),
    sa.Column('cron_expression', sa.String(length=255), server_default='', nullable=True, comment='cron执行表达式'),
    sa.Column('misfire_policy', sa.String(length=20), server_default='3', nullable=True, comment='计划执行错误策略（1立即执行 2执行一次 3放弃执行）'),
    sa.Column('concurrent', sa.CHAR(length=1), server_default='1', nullable=True, comment='是否并发执行（0允许 1禁止）'),
    sa.Column('status', sa.CHAR(length=1), server_default='0', nullable=True, comment='状态（0正常 1暂停）'),
    sa.Column('create_by', sa.String(length=64), server_default='', nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), server_default='', nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), server_default='', nullable=True, comment='备注信息'),
    sa.PrimaryKeyConstraint('job_id', 'job_name', 'job_group'),
    comment='定时任务调度表'
    )
    op.create_table('sys_job_log',
    sa.Column('job_log_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='任务日志ID'),
    sa.Column('job_name', sa.String(length=64), nullable=False, comment='任务名称'),
    sa.Column('job_group', sa.String(length=64), nullable=False, comment='任务组名'),
    sa.Column('job_executor', sa.String(length=64), nullable=False, comment='任务执行器'),
    sa.Column('invoke_target', sa.String(length=500), nullable=False, comment='调用目标字符串'),
    sa.Column('job_args', sa.String(length=255), server_default='', nullable=True, comment='位置参数'),
    sa.Column('job_kwargs', sa.String(length=255), server_default='', nullable=True, comment='关键字参数'),
    sa.Column('job_trigger', sa.String(length=255), server_default='', nullable=True, comment='任务触发器'),
    sa.Column('job_message', sa.String(length=500), nullable=True, comment='日志信息'),
    sa.Column('status', sa.CHAR(length=1), server_default='0', nullable=True, comment='执行状态（0正常 1失败）'),
    sa.Column('exception_info', sa.String(length=2000), server_default='', nullable=True, comment='异常信息'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('job_log_id'),
    comment='定时任务调度日志表'
    )
    op.create_table('sys_logininfor',
    sa.Column('info_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='访问ID'),
    sa.Column('user_name', sa.String(length=50), server_default='', nullable=True, comment='用户账号'),
    sa.Column('ipaddr', sa.String(length=128), server_default='', nullable=True, comment='登录IP地址'),
    sa.Column('login_location', sa.String(length=255), server_default='', nullable=True, comment='登录地点'),
    sa.Column('browser', sa.String(length=50), server_default='', nullable=True, comment='浏览器类型'),
    sa.Column('os', sa.String(length=50), server_default='', nullable=True, comment='操作系统'),
    sa.Column('status', sa.CHAR(length=1), server_default='0', nullable=True, comment='登录状态（0成功 1失败）'),
    sa.Column('msg', sa.String(length=255), server_default='', nullable=True, comment='提示消息'),
    sa.Column('login_time', sa.DateTime(), nullable=True, comment='访问时间'),
    sa.PrimaryKeyConstraint('info_id'),
    comment='系统访问记录'
    )
    op.create_index('idx_sys_logininfor_lt', 'sys_logininfor', ['login_time'], unique=False)
    op.create_index('idx_sys_logininfor_s', 'sys_logininfor', ['status'], unique=False)
    op.create_table('sys_menu',
    sa.Column('menu_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='菜单ID'),
    sa.Column('menu_name', sa.String(length=50), nullable=False, comment='菜单名称'),
    sa.Column('parent_id', sa.BigInteger(), server_default='0', nullable=True, comment='父菜单ID'),
    sa.Column('order_num', sa.Integer(), server_default='0', nullable=True, comment='显示顺序'),
    sa.Column('path', sa.String(length=200), server_default='', nullable=True, comment='路由地址'),
    sa.Column('component', sa.String(length=255), server_default=sa.text('NULL'), nullable=True, comment='组件路径'),
    sa.Column('query', sa.String(length=255), server_default=sa.text('NULL'), nullable=True, comment='路由参数'),
    sa.Column('route_name', sa.String(length=50), server_default='', nullable=True, comment='路由名称'),
    sa.Column('is_frame', sa.Integer(), server_default='1', nullable=True, comment='是否为外链（0是 1否）'),
    sa.Column('is_cache', sa.Integer(), server_default='0', nullable=True, comment='是否缓存（0缓存 1不缓存）'),
    sa.Column('menu_type', sa.CHAR(length=1), server_default='', nullable=True, comment='菜单类型（M目录 C菜单 F按钮）'),
    sa.Column('visible', sa.CHAR(length=1), server_default='0', nullable=True, comment='菜单状态（0显示 1隐藏）'),
    sa.Column('status', sa.CHAR(length=1), server_default='0', nullable=True, comment='菜单状态（0正常 1停用）'),
    sa.Column('perms', sa.String(length=100), server_default=sa.text('NULL'), nullable=True, comment='权限标识'),
    sa.Column('icon', sa.String(length=100), server_default='#', nullable=True, comment='菜单图标'),
    sa.Column('create_by', sa.String(length=64), server_default='', nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), server_default='', nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), server_default='', nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('menu_id'),
    comment='菜单权限表'
    )
    op.create_table('sys_notice',
    sa.Column('notice_id', sa.Integer(), autoincrement=True, nullable=False, comment='公告ID'),
    sa.Column('notice_title', sa.String(length=50), nullable=False, comment='公告标题'),
    sa.Column('notice_type', sa.CHAR(length=1), nullable=False, comment='公告类型（1通知 2公告）'),
    sa.Column('notice_content', sa.LargeBinary(), nullable=True, comment='公告内容'),
    sa.Column('status', sa.CHAR(length=1), server_default='0', nullable=True, comment='公告状态（0正常 1关闭）'),
    sa.Column('create_by', sa.String(length=64), server_default='', nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), server_default='', nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=255), server_default=sa.text('NULL'), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('notice_id'),
    comment='通知公告表'
    )
    op.create_table('sys_oper_log',
    sa.Column('oper_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='日志主键'),
    sa.Column('title', sa.String(length=50), server_default='', nullable=True, comment='模块标题'),
    sa.Column('business_type', sa.Integer(), server_default='0', nullable=True, comment='业务类型（0其它 1新增 2修改 3删除）'),
    sa.Column('method', sa.String(length=100), server_default='', nullable=True, comment='方法名称'),
    sa.Column('request_method', sa.String(length=10), server_default='', nullable=True, comment='请求方式'),
    sa.Column('operator_type', sa.Integer(), server_default='0', nullable=True, comment='操作类别（0其它 1后台用户 2手机端用户）'),
    sa.Column('oper_name', sa.String(length=50), server_default='', nullable=True, comment='操作人员'),
    sa.Column('dept_name', sa.String(length=50), server_default='', nullable=True, comment='部门名称'),
    sa.Column('oper_url', sa.String(length=255), server_default='', nullable=True, comment='请求URL'),
    sa.Column('oper_ip', sa.String(length=128), server_default='', nullable=True, comment='主机地址'),
    sa.Column('oper_location', sa.String(length=255), server_default='', nullable=True, comment='操作地点'),
    sa.Column('oper_param', sa.String(length=2000), server_default='', nullable=True, comment='请求参数'),
    sa.Column('json_result', sa.String(length=2000), server_default='', nullable=True, comment='返回参数'),
    sa.Column('status', sa.Integer(), server_default='0', nullable=True, comment='操作状态（0正常 1异常）'),
    sa.Column('error_msg', sa.String(length=2000), server_default='', nullable=True, comment='错误消息'),
    sa.Column('oper_time', sa.DateTime(), nullable=True, comment='操作时间'),
    sa.Column('cost_time', sa.BigInteger(), server_default='0', nullable=True, comment='消耗时间'),
    sa.PrimaryKeyConstraint('oper_id'),
    comment='操作日志记录'
    )
    op.create_index('idx_sys_oper_log_bt', 'sys_oper_log', ['business_type'], unique=False)
    op.create_index('idx_sys_oper_log_ot', 'sys_oper_log', ['oper_time'], unique=False)
    op.create_index('idx_sys_oper_log_s', 'sys_oper_log', ['status'], unique=False)
    op.create_table('sys_post',
    sa.Column('post_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='岗位ID'),
    sa.Column('post_code', sa.String(length=64), nullable=False, comment='岗位编码'),
    sa.Column('post_name', sa.String(length=50), nullable=False, comment='岗位名称'),
    sa.Column('post_sort', sa.Integer(), nullable=False, comment='显示顺序'),
    sa.Column('status', sa.CHAR(length=1), nullable=False, comment='状态（0正常 1停用）'),
    sa.Column('create_by', sa.String(length=64), server_default='', nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), server_default='', nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), server_default=sa.text('NULL'), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('post_id'),
    comment='岗位信息表'
    )
    op.create_table('sys_role',
    sa.Column('role_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='角色ID'),
    sa.Column('role_name', sa.String(length=30), nullable=False, comment='角色名称'),
    sa.Column('role_key', sa.String(length=100), nullable=False, comment='角色权限字符串'),
    sa.Column('role_sort', sa.Integer(), nullable=False, comment='显示顺序'),
    sa.Column('data_scope', sa.CHAR(length=1), server_default='1', nullable=True, comment='数据范围（1：全部数据权限 2：自定数据权限 3：本部门数据权限 4：本部门及以下数据权限）'),
    sa.Column('menu_check_strictly', sa.SmallInteger(), server_default='1', nullable=True, comment='菜单树选择项是否关联显示'),
    sa.Column('dept_check_strictly', sa.SmallInteger(), server_default='1', nullable=True, comment='部门树选择项是否关联显示'),
    sa.Column('status', sa.CHAR(length=1), nullable=False, comment='角色状态（0正常 1停用）'),
    sa.Column('del_flag', sa.CHAR(length=1), server_default='0', nullable=True, comment='删除标志（0代表存在 2代表删除）'),
    sa.Column('create_by', sa.String(length=64), server_default='', nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), server_default='', nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), server_default=sa.text('NULL'), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('role_id'),
    comment='角色信息表'
    )
    op.create_table('sys_role_dept',
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色ID'),
    sa.Column('dept_id', sa.BigInteger(), nullable=False, comment='部门ID'),
    sa.PrimaryKeyConstraint('role_id', 'dept_id'),
    comment='角色和部门关联表'
    )
    op.create_table('sys_role_menu',
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色ID'),
    sa.Column('menu_id', sa.BigInteger(), nullable=False, comment='菜单ID'),
    sa.PrimaryKeyConstraint('role_id', 'menu_id'),
    comment='角色和菜单关联表'
    )
    op.create_table('sys_user',
    sa.Column('user_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='用户ID'),
    sa.Column('dept_id', sa.BigInteger(), nullable=True, comment='部门ID'),
    sa.Column('user_name', sa.String(length=30), nullable=False, comment='用户账号'),
    sa.Column('nick_name', sa.String(length=30), nullable=False, comment='用户昵称'),
    sa.Column('user_type', sa.String(length=2), server_default='00', nullable=True, comment='用户类型（00系统用户）'),
    sa.Column('email', sa.String(length=50), server_default='', nullable=True, comment='用户邮箱'),
    sa.Column('phonenumber', sa.String(length=11), server_default='', nullable=True, comment='手机号码'),
    sa.Column('sex', sa.CHAR(length=1), server_default='0', nullable=True, comment='用户性别（0男 1女 2未知）'),
    sa.Column('avatar', sa.String(length=100), server_default='', nullable=True, comment='头像地址'),
    sa.Column('password', sa.String(length=100), server_default='', nullable=True, comment='密码'),
    sa.Column('status', sa.CHAR(length=1), server_default='0', nullable=True, comment='帐号状态（0正常 1停用）'),
    sa.Column('del_flag', sa.CHAR(length=1), server_default='0', nullable=True, comment='删除标志（0代表存在 2代表删除）'),
    sa.Column('login_ip', sa.String(length=128), server_default='', nullable=True, comment='最后登录IP'),
    sa.Column('login_date', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('pwd_update_date', sa.DateTime(), nullable=True, comment='密码最后更新时间'),
    sa.Column('create_by', sa.String(length=64), server_default='', nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), server_default='', nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), server_default=sa.text('NULL'), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('user_id'),
    comment='用户信息表'
    )
    op.create_table('sys_user_post',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('post_id', sa.BigInteger(), nullable=False, comment='岗位ID'),
    sa.PrimaryKeyConstraint('user_id', 'post_id'),
    comment='用户与岗位关联表'
    )
    op.create_table('sys_user_role',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色ID'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    comment='用户和角色关联表'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sys_user_role')
    op.drop_table('sys_user_post')
    op.drop_table('sys_user')
    op.drop_table('sys_role_menu')
    op.drop_table('sys_role_dept')
    op.drop_table('sys_role')
    op.drop_table('sys_post')
    op.drop_index('idx_sys_oper_log_s', table_name='sys_oper_log')
    op.drop_index('idx_sys_oper_log_ot', table_name='sys_oper_log')
    op.drop_index('idx_sys_oper_log_bt', table_name='sys_oper_log')
    op.drop_table('sys_oper_log')
    op.drop_table('sys_notice')
    op.drop_table('sys_menu')
    op.drop_index('idx_sys_logininfor_s', table_name='sys_logininfor')
    op.drop_index('idx_sys_logininfor_lt', table_name='sys_logininfor')
    op.drop_table('sys_logininfor')
    op.drop_table('sys_job_log')
    op.drop_table('sys_job')
    op.drop_table('sys_dict_type')
    op.drop_table('sys_dict_data')
    op.drop_table('sys_dept')
    op.drop_table('sys_config')
    op.drop_table('gen_table_column')
    op.drop_table('gen_table')
    # ### end Alembic commands ###
